version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  build:
    commands:
      - docker build -t my-php-app .
      - $(aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r1g5u8w6)
      - docker tag my-php-app:latest public.ecr.aws/r1g5u8w6/demo:latest
      - docker push public.ecr.aws/r1g5u8w6/demo:latest
artifacts:
  files: '**/*'
